#!/bin/bash
#
#  installer prefix

prefix=$1
pkgdir=$prefix/TclLibs/rest
docdir=$prefix/share/rest

mkdir -p $pkgdir

tar czf - bin lib custom htdocs htdocs_2 startServer.tcl pkgIndex.tcl | \
    (cd $pkgdir; tar xzf -)

mkdir -p $docdir

docbook2pdf -o $docdir  restdocs.xml 

