#!/usr/bin/tclsh
#
# Description:
#  This is a short script for converting text files between DOS and Unix
#  formats. DOS text files generally have ^M characters as their newline
#  characters when viewed in Unix, which can cause some problems with some
#  files. In particular, it makes building SpecTcl difficult as the Makefiles
#  will give up during makedepends. This script gets rid of those annoying 
#  little things quickly and painlessly. It's basically the same thing as 
#  fromdos, found on some Unix distributions, but we wanted our own to
#  distribute with our open source apps that other people will want to build
#  on their own systems.
#
# Usage:
#  fixdos [file1...]    (Note that multiple file names may be entered with
#                        full path supplied)
#

proc FromDos {numargs cmdargs} {
    if {$numargs < 1} {
	puts "Usage: fromdos <filename>"
	exit
    } else {
	foreach fileitem $cmdargs {
	    set filename $fileitem
	    if [catch {set file1 [open $filename RDWR]} result] {
		puts stderr "File $file1 does not appear to exist"
		exit
	    }
	    set file2 [open $filename.2 w]
	    foreach line [split [read $file1] \n] {
		puts $file2 $line
	    }
	    exec rm -f $filename
	    exec mv $filename.2 $filename
	    exec rm -f $filename.2
	    close $file1
	    close $file2
	}
    }
}

FromDos $argc $argv
