#!/bin/bash -xe


rm -rf ${WORKSPACE}/3.4

amversion=`grep AM_INIT_AUTOMAKE configure.ac | cut -f2 -d" " | sed s/,//`
acversion=`grep AC_INIT configure.ac | cut -f2 -d"," | sed s/,// | sed s/")"//`
rm -rf SpecTcl-${amversion} SpecTcl-${acversion}

tarball=SpecTcl-${amversion}.tar.gz
version=${amversion}
if test ! -e ${tarball}
then
   tarball=SpecTcl-${acversion}.tar.gz
   version=${acversion}
fi
echo $tarball


tar xzf SpecTcl-${version}.tar.gz
cd SpecTcl-${version}

./configure --prefix=${WORKSPACE}/3.4
make clean all
make install
make check
make installcheck

rm -rf SpecTcl-${version}
rm -rf ${WORKSPACE}/3.4
