#!/bin/bash -xe


rm -rf ${WORKSPACE}/3.4

version=`grep AM_INIT_AUTOMAKE configure.ac | cut -f2 -d" " | sed s/,//`

rm -rf SpecTcl-${version}

tar xzf SpecTcl-${version}.tar.gz
cd SpecTcl-${version}

./configure --prefix=${WORKSPACE}/3.4
make clean all
make install
make check
make installcheck

rm -rf SpecTcl-${version}
rm -rf ${WORKSPACE}/3.4
