#!/bin/bash

# Incorporate a tag of libtcl++
# Most recent good tag:  libtclplus-v4.3-002

tag=$1
REPOSITORY="https://github.com/FRIBDAQ/libtclplus"
TARGET="libtcl"

rm -rf ${TARGET}

# if not argument is provided, use default value
if [[ ! $tag ]];
then
  tag=`cat LIBTCL_VERSION`
fi
git clone ${REPOSITORY} ${TARGET}
(cd ${TARGET}; git checkout $tag)
(cd ${TARGET}; autoreconf -if)
