#!/bin/bash -xe


target=${WORKSPACE}/${GIT_BRANCH}-${BUILD_NUMBER}-fromdist
rm -rf ${target}

amversion=`grep AM_INIT_AUTOMAKE configure.ac | cut -f2 -d" " | sed s/,//`
acversion=`grep AC_INIT configure.ac | cut -f2 -d"," | sed s/,// | sed s/")"//`
rm -rf SpecTcl-${amversion} SpecTcl-${acversion}

tarball=SpecTcl-${amversion}.tar.gz
version=${amversion}
if test ! -e ${tarball}
then
   tarball=spectcl-${acversion}.tar.gz
   version=${acversion}
fi
echo ${tarball}


tar xzf ${tarball}
cd `basename ${tarball} .tar.gz`

./configure --prefix=${target}
make clean all
make install
make check
make installcheck

rm -rf `basename ${tarball} .tar.gz`

