#!/bin/bash -xe


rm -rf ${WORKSPACE}/sptrunk

version=`grep AM_INIT_AUTOMAKE configure.ac | cut -f2 -d" " | sed -e s/,// | sed -e 's/)//'`

rm -rf SpecTcl-${version}

tar xzf SpecTcl-${version}.tar.gz
cd SpecTcl-${version}

./configure --prefix=${WORKSPACE}/sptrunk
make clean all
make install
make check
make installcheck

rm -rf SpecTcl-${version}
rm -rf ${WORKSPACE}/sptrunk
