/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.4 on Tue Dec 17 13:25:15 2019
 */

#include "sipAPICPyConverter.h"

#line 285 "CPyConverter.sip"
#include <vector>
#line 12 "./sipCPyConverterstdvector2200.cpp"



extern "C" {static void assign_std_vector_2200(void *, SIP_SSIZE_T, const void *);}
static void assign_std_vector_2200(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<std::vector<float> *>(sipDst)[sipDstIdx] = *reinterpret_cast<const std::vector<float> *>(sipSrc);
}


extern "C" {static void *array_std_vector_2200(SIP_SSIZE_T);}
static void *array_std_vector_2200(SIP_SSIZE_T sipNrElem)
{
    return new std::vector<float>[sipNrElem];
}


extern "C" {static void *copy_std_vector_2200(const void *, SIP_SSIZE_T);}
static void *copy_std_vector_2200(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new std::vector<float>(reinterpret_cast<const std::vector<float> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_std_vector_2200(void *, int);}
static void release_std_vector_2200(void *ptr, int)
{
    delete reinterpret_cast<std::vector<float> *>(ptr);
}



extern "C" {static int convertTo_std_vector_2200(PyObject *, void **, int *, PyObject *);}
static int convertTo_std_vector_2200(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    std::vector<float> **sipCppPtr = reinterpret_cast<std::vector<float> **>(sipCppPtrV);

#line 309 "CPyConverter.sip"
 // Check if type is compatible
 if (sipIsErr == NULL) {
   if (!PyList_Check(sipPy)) {
     return 0;
   }
   for (SIP_SSIZE_T i = 0; i < PyList_GET_SIZE(sipPy); ++i) {
     PyObject *item = PyList_GET_ITEM(sipPy, i);
     if (!PyNumber_Check(item)) {
       //printErrorMessage("TypeError : object in list of type " + std::string(item->ob_type->tp_name) + " can not be converted to float");
       return 0;
     }
   }
   return 1;
 }

 // Convert Python list of numbers to a std::vector<double>
 std::vector<float> *v = new std::vector<float>();
 for (SIP_SSIZE_T i = 0; i < PyList_GET_SIZE(sipPy); ++i) {
   PyObject *f = PyNumber_Float(PyList_GET_ITEM(sipPy, i));
   v->push_back(float(PyFloat_AsDouble(f)));
   Py_XDECREF(f);
 }

 *sipCppPtr = v;
 return sipGetState(sipTransferObj);
#line 77 "./sipCPyConverterstdvector2200.cpp"
}


extern "C" {static PyObject *convertFrom_std_vector_2200(void *, PyObject *);}
static PyObject *convertFrom_std_vector_2200(void *sipCppV, PyObject *)
{
   std::vector<float> *sipCpp = reinterpret_cast<std::vector<float> *>(sipCppV);

#line 289 "CPyConverter.sip"
 PyObject *l;

 // Create the Python list of the correct length.
 if ((l = PyList_New(sipCpp -> size())) == NULL) {
  return NULL;
 }

 // Go through each element in the C++ instance and convert it to a
 // wrapped object.
 int i = 0;
 for (std::vector<float>::iterator iter = sipCpp->begin(); iter != sipCpp->end(); ++iter) {
     // Add the wrapper to the list.
     PyList_SET_ITEM(l, i++, PyFloat_FromDouble(*iter));
 }

 // Return the Python list.
 return l;
#line 104 "./sipCPyConverterstdvector2200.cpp"
}


sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_2200 = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_92,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_std_vector_2200,
    array_std_vector_2200,
    copy_std_vector_2200,
    release_std_vector_2200,
    convertTo_std_vector_2200,
    convertFrom_std_vector_2200
};
