/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.4 on Tue Dec 17 13:25:15 2019
 */

#include "sipAPICPyConverter.h"

#line 619 "CPyConverter.sip"
#include <vector>
#line 12 "./sipCPyConverterstdvector0100stdstring.cpp"

#line 684 "CPyConverter.sip"
#include <string>
#line 16 "./sipCPyConverterstdvector0100stdstring.cpp"


extern "C" {static void assign_std_vector_0100std_string(void *, SIP_SSIZE_T, const void *);}
static void assign_std_vector_0100std_string(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<std::vector<std::string> *>(sipDst)[sipDstIdx] = *reinterpret_cast<const std::vector<std::string> *>(sipSrc);
}


extern "C" {static void *array_std_vector_0100std_string(SIP_SSIZE_T);}
static void *array_std_vector_0100std_string(SIP_SSIZE_T sipNrElem)
{
    return new std::vector<std::string>[sipNrElem];
}


extern "C" {static void *copy_std_vector_0100std_string(const void *, SIP_SSIZE_T);}
static void *copy_std_vector_0100std_string(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new std::vector<std::string>(reinterpret_cast<const std::vector<std::string> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_std_vector_0100std_string(void *, int);}
static void release_std_vector_0100std_string(void *ptr, int)
{
    delete reinterpret_cast<std::vector<std::string> *>(ptr);
}



extern "C" {static int convertTo_std_vector_0100std_string(PyObject *, void **, int *, PyObject *);}
static int convertTo_std_vector_0100std_string(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    std::vector<std::string> **sipCppPtr = reinterpret_cast<std::vector<std::string> **>(sipCppPtrV);

#line 649 "CPyConverter.sip"
  // Check if type is compatible
  if (sipIsErr == NULL) {
    if (!PyList_Check(sipPy)) {
      return 0;
    }
    for (SIP_SSIZE_T i = 0; i < PyList_GET_SIZE(sipPy); ++i) {
      PyObject *item = PyList_GET_ITEM(sipPy, i);
      if (!PyBool_Check(item)) {
        //printErrorMessage("TypeError : object in list of type " + std::string(item->ob_type->tp_name) + " can not be converted to bool");
        return 0;
      }
    }
    return 1;
  }

  // Convert Python list of string to a std::vector<std::string>
  std::vector<std::string> *v = new std::vector<std::string>();
  for (SIP_SSIZE_T i = 0; i < PyList_GET_SIZE(sipPy); ++i) {
    PyObject *item = PyList_GET_ITEM(sipPy, i);	      
    v->push_back((std::string)PyBytes_AsString(item));
  }

  *sipCppPtr = v;
  return sipGetState(sipTransferObj);
#line 79 "./sipCPyConverterstdvector0100stdstring.cpp"
}


extern "C" {static PyObject *convertFrom_std_vector_0100std_string(void *, PyObject *);}
static PyObject *convertFrom_std_vector_0100std_string(void *sipCppV, PyObject *)
{
   std::vector<std::string> *sipCpp = reinterpret_cast<std::vector<std::string> *>(sipCppV);

#line 623 "CPyConverter.sip"
  PyObject *l;

  // Create the Python list of the correct length.
  if ((l = PyList_New(sipCpp -> size())) == NULL) {
    return NULL;
  }

  // Go through each element in the C++ instance and convert it to a
  // wrapped object.
  int i = 0;
  for (std::vector<std::string>::iterator iter = sipCpp->begin(); iter != sipCpp->end(); ++iter) {
    PyObject* newstring;
    newstring = PyUnicode_DecodeUTF8(iter->c_str(), iter->length(), NULL);
    if(newstring == NULL) {
        PyErr_Clear();
        newstring = PyBytes_FromString(iter->c_str());
    }
    // Add the wrapper to the list.    
    PyList_SET_ITEM(l, i, newstring);
  }

  // Return the Python list.
  return l;
#line 112 "./sipCPyConverterstdvector0100stdstring.cpp"
}


sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_0100std_string = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_27,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_std_vector_0100std_string,
    array_std_vector_0100std_string,
    copy_std_vector_0100std_string,
    release_std_vector_0100std_string,
    convertTo_std_vector_0100std_string,
    convertFrom_std_vector_0100std_string
};
