C
C Facility:
C   Xamine  -- NSCL display program.
C Abstract:
C    XAMINESHARE.FOR:
C      This file is part of the VAX/VMS fortran bindings for Xamine.
C      In particular, this file provdes definitions for the 
C      Xamine shared memory region.
C Author:
C   Ron Fox
C   NSCL
C   Michigan State University
C   East Lansing, MI 48824-1321
C   October 18, 1993
C
C
C -- The includer must provide the value of:
C    XAMINE_SPECBYTES -- number of spectrum bytes.
C
C	THE  COMMON AREA FOR THE XAMINE DISPLAY PROGRAM
C
C
	INTEGER   XAMINE_ISMAX, XAMINE_SPECBYTES, XAMINE_WORDS, XAMINE_LONGS
	PARAMETER (XAMINE_ISMAX = 5000)
	PARAMETER (XAMINE_SPECBYTES = 1048576 * 8)
	PARAMETER (XAMINE_WORDS = XAMINE_SPECBYTES / 2)
	PARAMETER (XAMINE_LONGS = XAMINE_SPECBYTES / 4)

C
C	PARAMETERS TO DEFINE THE SPECTRUM TYPES:
C
	INTEGER   XAMINE_UNDEFINED, XAMINE_ONEDLONG, XAMINE_ONEDWORD
	INTEGER   XAMINE_TWODBYTE, XAMINE_TWODWORD
	PARAMETER (XAMINE_UNDEFINED = 0)
	PARAMETER (XAMINE_ONEDLONG  = 4)
	PARAMETER (XAMINE_ONEDWORD  = 2)
	PARAMETER (XAMINE_TWODWORD  = 3)
	PARAMETER (XAMINE_TWODBYTE  = 1)
C

	BYTE      XAMINE_DATA1 (XAMINE_SPECBYTES)
	INTEGER*2 XAMINE_DATA2 (XAMINE_WORDS)
	INTEGER*4 XAMINE_DATA4 (XAMINE_LONGS)
	INTEGER*2 XAMINE_XY (2, XAMINE_ISMAX)
	BYTE      XAMINE_TITLES (72, XAMINE_ISMAX)
	INTEGER   XAMINE_OFFSETS (XAMINE_ISMAX)
	INTEGER   XAMINE_TYPES (XAMINE_ISMAX)

	POINTER   (XAMINE_XYPTR, XAMINE_XY)
	POINTER   (XAMINE_TITLESPTR,  XAMINE_TITLES)
	POINTER   (XAMINE_OFFSETSPTR, XAMINE_OFFSETS)
	POINTER   (XAMINE_TYPESPTR,   XAMINE_TYPES)
	POINTER   (XAMINE_DATA1PTR,   XAMINE_DATA1)
	POINTER   (XAMINE_DATA2PTR,   XAMINE_DATA2)
	POINTER   (XAMINE_DATA4PTR,   XAMINE_DATA4)

	COMMON / XAMINE_SHARED / XAMINE_XYPTR, XAMINE_TITLESPTR, 
	1	XAMINE_OFFSETSPTR, XAMINE_TYPESPTR, XAMINE_DATA1PTR,
	1       XAMINE_DATA2PTR, XAMINE_DATA4PTR

C
C        Define functions:
C

	INTEGER F77XAMINE_CREATESHAREDMEMORY
	INTEGER F77XAMINE_START
	INTEGER F77XAMINE_STOP
	LOGICAL F77XAMINE_ALIVE
	INTEGER F77XAMINE_MAPMEMORY
	INTEGER F77XAMINE_ENTERGATE
	INTEGER F77XAMINE_REMOVEGATE
	INTEGER F77XAMINE_STARTSEARCH
	LOGICAL F77XAMINE_NEXTGATE
	INTEGER F77XAMINE_READGATE
	INTEGER F77XAMINE_POLLFORGATE
	INTEGER F77XAMINE_READ
	INTEGER F77XAMINE_WAIT
	INTEGER F77XAMINE_INIT

	INTEGER F77XAMINE_ALLOCATESPECTRUM
	INTEGER F77XAMINE_RESERVESPECTRUM
	INTEGER F77XAMINE_ALLOCMEMORY
	INTEGER F77XAMINE_ALLOCATE1D
	INTEGER F77XAMINE_ALLOCATE2D
	INTEGER F77XAMINE_ENTERPEAKMARKER
C
C	    Types of gate entities:
C









