/*
 * Internal module API header file.
 *
 * Generated by SIP 4.16.4 on Fri Dec  6 15:49:47 2019
 */

#ifndef _CPyConverterAPI_H
#define _CPyConverterAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_0 0
#define sipName_0 &sipStrings_CPyConverter[0]
#define sipNameNr_27 27
#define sipName_27 &sipStrings_CPyConverter[27]
#define sipNameNr_47 47
#define sipName_47 &sipStrings_CPyConverter[47]
#define sipNameNr_vectorToList_Float 66
#define sipName_vectorToList_Float &sipStrings_CPyConverter[66]
#define sipNameNr_85 85
#define sipName_85 &sipStrings_CPyConverter[85]
#define sipNameNr_103 103
#define sipName_103 &sipStrings_CPyConverter[103]
#define sipNameNr_121 121
#define sipName_121 &sipStrings_CPyConverter[121]
#define sipNameNr_139 139
#define sipName_139 &sipStrings_CPyConverter[139]
#define sipNameNr_vectorToList_Int 156
#define sipName_vectorToList_Int &sipStrings_CPyConverter[156]
#define sipNameNr_getRandomNumber 173
#define sipName_getRandomNumber &sipStrings_CPyConverter[173]
#define sipNameNr_CPyConverter 189
#define sipName_CPyConverter &sipStrings_CPyConverter[189]
#define sipNameNr_std__string 202
#define sipName_std__string &sipStrings_CPyConverter[202]
#define sipNameNr_generate 214
#define sipName_generate &sipStrings_CPyConverter[214]
#define sipNameNr_string 207
#define sipName_string &sipStrings_CPyConverter[207]
#define sipNameNr_print 223
#define sipName_print &sipStrings_CPyConverter[223]
#define sipNameNr_m_v 229
#define sipName_m_v &sipStrings_CPyConverter[229]

#define sipMalloc                   sipAPI_CPyConverter->api_malloc
#define sipFree                     sipAPI_CPyConverter->api_free
#define sipBuildResult              sipAPI_CPyConverter->api_build_result
#define sipCallMethod               sipAPI_CPyConverter->api_call_method
#define sipCallErrorHandler         sipAPI_CPyConverter->api_call_error_handler
#define sipParseResultEx            sipAPI_CPyConverter->api_parse_result_ex
#define sipParseResult              sipAPI_CPyConverter->api_parse_result
#define sipParseArgs                sipAPI_CPyConverter->api_parse_args
#define sipParseKwdArgs             sipAPI_CPyConverter->api_parse_kwd_args
#define sipParsePair                sipAPI_CPyConverter->api_parse_pair
#define sipCommonDtor               sipAPI_CPyConverter->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_CPyConverter->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_CPyConverter->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_CPyConverter->api_convert_to_void_ptr
#define sipAddException             sipAPI_CPyConverter->api_add_exception
#define sipNoFunction               sipAPI_CPyConverter->api_no_function
#define sipNoMethod                 sipAPI_CPyConverter->api_no_method
#define sipAbstractMethod           sipAPI_CPyConverter->api_abstract_method
#define sipBadClass                 sipAPI_CPyConverter->api_bad_class
#define sipBadCatcherResult         sipAPI_CPyConverter->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_CPyConverter->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_CPyConverter->api_bad_operator_arg
#define sipTrace                    sipAPI_CPyConverter->api_trace
#define sipTransferBack             sipAPI_CPyConverter->api_transfer_back
#define sipTransferTo               sipAPI_CPyConverter->api_transfer_to
#define sipTransferBreak            sipAPI_CPyConverter->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_CPyConverter->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_CPyConverter->api_wrapper_type
#define sipWrapperType_Type         sipAPI_CPyConverter->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_CPyConverter->api_voidptr_type
#define sipGetPyObject              sipAPI_CPyConverter->api_get_pyobject
#define sipGetAddress               sipAPI_CPyConverter->api_get_address
#define sipGetMixinAddress          sipAPI_CPyConverter->api_get_mixin_address
#define sipGetCppPtr                sipAPI_CPyConverter->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_CPyConverter->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_CPyConverter->api_is_py_method
#define sipCallHook                 sipAPI_CPyConverter->api_call_hook
#define sipEndThread                sipAPI_CPyConverter->api_end_thread
#define sipConnectRx                sipAPI_CPyConverter->api_connect_rx
#define sipDisconnectRx             sipAPI_CPyConverter->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_CPyConverter->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_CPyConverter->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_CPyConverter->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_CPyConverter->api_add_type_instance
#define sipFreeSipslot              sipAPI_CPyConverter->api_free_sipslot
#define sipSameSlot                 sipAPI_CPyConverter->api_same_slot
#define sipPySlotExtend             sipAPI_CPyConverter->api_pyslot_extend
#define sipConvertRx                sipAPI_CPyConverter->api_convert_rx
#define sipAddDelayedDtor           sipAPI_CPyConverter->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_CPyConverter->api_can_convert_to_type
#define sipConvertToType            sipAPI_CPyConverter->api_convert_to_type
#define sipForceConvertToType       sipAPI_CPyConverter->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_CPyConverter->api_can_convert_to_enum
#define sipReleaseType              sipAPI_CPyConverter->api_release_type
#define sipConvertFromType          sipAPI_CPyConverter->api_convert_from_type
#define sipConvertFromNewType       sipAPI_CPyConverter->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_CPyConverter->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_CPyConverter->api_convert_from_enum
#define sipGetState                 sipAPI_CPyConverter->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_CPyConverter->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_CPyConverter->api_export_symbol
#define sipImportSymbol             sipAPI_CPyConverter->api_import_symbol
#define sipFindType                 sipAPI_CPyConverter->api_find_type
#define sipFindNamedEnum            sipAPI_CPyConverter->api_find_named_enum
#define sipBytes_AsChar             sipAPI_CPyConverter->api_bytes_as_char
#define sipBytes_AsString           sipAPI_CPyConverter->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_CPyConverter->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_CPyConverter->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_CPyConverter->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_CPyConverter->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_CPyConverter->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_CPyConverter->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_CPyConverter->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_CPyConverter->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_CPyConverter->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_CPyConverter->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_CPyConverter->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_CPyConverter->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_CPyConverter->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_CPyConverter->api_save_slot
#define sipClearAnySlotReference    sipAPI_CPyConverter->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_CPyConverter->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_CPyConverter->api_deprecated
#define sipKeepReference            sipAPI_CPyConverter->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_CPyConverter->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_CPyConverter->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_CPyConverter->api_type_from_py_type_object
#define sipTypeScope                sipAPI_CPyConverter->api_type_scope
#define sipResolveTypedef           sipAPI_CPyConverter->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_CPyConverter->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_CPyConverter->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_CPyConverter->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_CPyConverter->api_enable_autoconversion
#define sipInitMixin                sipAPI_CPyConverter->api_init_mixin
#define sipExportModule             sipAPI_CPyConverter->api_export_module
#define sipInitModule               sipAPI_CPyConverter->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_CPyConverter->api_map_string_to_class
#define sipMapIntToClass            sipAPI_CPyConverter->api_map_int_to_class
#define sipFindClass                sipAPI_CPyConverter->api_find_class
#define sipFindMappedType           sipAPI_CPyConverter->api_find_mapped_type
#define sipConvertToArray           sipAPI_CPyConverter->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_CPyConverter->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_CPyConverter->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_CPyConverter[];

#define sipType_CPyConverter              sipModuleAPI_CPyConverter.em_types[0]
#define sipClass_CPyConverter             sipModuleAPI_CPyConverter.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_CPyConverter_CPyConverter;

#define sipType_std_string      sipModuleAPI_CPyConverter.em_types[1]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_string;

#define sipType_std_vector_2600      sipModuleAPI_CPyConverter.em_types[2]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_2600;

#define sipType_std_vector_2100      sipModuleAPI_CPyConverter.em_types[8]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_2100;

#define sipType_std_vector_2000      sipModuleAPI_CPyConverter.em_types[6]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_2000;

#define sipType_std_vector_1900      sipModuleAPI_CPyConverter.em_types[7]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_1900;

#define sipType_std_vector_1800      sipModuleAPI_CPyConverter.em_types[5]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_1800;

#define sipType_std_vector_2200      sipModuleAPI_CPyConverter.em_types[4]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_2200;

#define sipType_std_vector_2400      sipModuleAPI_CPyConverter.em_types[3]

extern sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_2400;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_CPyConverter;
extern sipExportedModuleDef sipModuleAPI_CPyConverter;

#endif
