/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.4 on Fri Dec  6 15:49:47 2019
 */

#include "sipAPICPyConverter.h"

#line 396 "CPyConverter.sip"
#include <vector>
#line 12 "./sipCPyConverterstdvector1900.cpp"



extern "C" {static void assign_std_vector_1900(void *, SIP_SSIZE_T, const void *);}
static void assign_std_vector_1900(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<std::vector<uint> *>(sipDst)[sipDstIdx] = *reinterpret_cast<const std::vector<uint> *>(sipSrc);
}


extern "C" {static void *array_std_vector_1900(SIP_SSIZE_T);}
static void *array_std_vector_1900(SIP_SSIZE_T sipNrElem)
{
    return new std::vector<uint>[sipNrElem];
}


extern "C" {static void *copy_std_vector_1900(const void *, SIP_SSIZE_T);}
static void *copy_std_vector_1900(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new std::vector<uint>(reinterpret_cast<const std::vector<uint> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_std_vector_1900(void *, int);}
static void release_std_vector_1900(void *ptr, int)
{
    delete reinterpret_cast<std::vector<uint> *>(ptr);
}



extern "C" {static int convertTo_std_vector_1900(PyObject *, void **, int *, PyObject *);}
static int convertTo_std_vector_1900(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    std::vector<uint> **sipCppPtr = reinterpret_cast<std::vector<uint> **>(sipCppPtrV);

#line 420 "CPyConverter.sip"
  // Check if type is compatible
  if (sipIsErr == NULL) {
    if (!PyList_Check(sipPy)) {
      return 0;
    }
    for (SIP_SSIZE_T i = 0; i < PyList_GET_SIZE(sipPy); ++i) {
      PyObject *item = PyList_GET_ITEM(sipPy, i);
#if PY_MAJOR_VERSION >= 3
     if (!PyLong_Check(item)) {
#else
        if (!PyLong_Check(item) && !PyInt_Check(item)) {
#endif
          //printErrorMessage("TypeError : object in list of type " + std::string(item->ob_type->tp_name) + " can not be converted to int");
          return 0;
        }
      }
      return 1;
    }

    // Convert Python list of integers to a std::vector<int>
    std::vector<unsigned int> *v = new std::vector<unsigned int>();
    for (SIP_SSIZE_T i = 0; i < PyList_GET_SIZE(sipPy); ++i) {
#if PY_MAJOR_VERSION >= 3
      v->push_back(uint(PyLong_AsUnsignedLong(PyList_GET_ITEM(sipPy, i))));
#else
      PyObject *item = PyList_GET_ITEM(sipPy, i);
      if (PyLong_Check(item)) {
        v->push_back(uint(PyLong_AsUnsignedLong(item)));
      } else {
        v->push_back(uint(PyInt_AsUnsignedLongMask(item)));
      }
#endif
    }

    *sipCppPtr = v;
    return sipGetState(sipTransferObj);
#line 88 "./sipCPyConverterstdvector1900.cpp"
}


extern "C" {static PyObject *convertFrom_std_vector_1900(void *, PyObject *);}
static PyObject *convertFrom_std_vector_1900(void *sipCppV, PyObject *)
{
   std::vector<uint> *sipCpp = reinterpret_cast<std::vector<uint> *>(sipCppV);

#line 400 "CPyConverter.sip"
  PyObject *l;

  // Create the Python list of the correct length.
  if ((l = PyList_New(sipCpp -> size())) == NULL) {
    return NULL;
  }

  // Go through each element in the C++ instance and convert it to a
  // wrapped object.
  int i = 0;
  for (std::vector<unsigned int>::iterator iter = sipCpp->begin(); iter != sipCpp->end(); ++iter) {
    // Add the wrapper to the list.
    PyList_SET_ITEM(l, i++, PyLong_FromUnsignedLong(*iter));
  }

  // Return the Python list.
  return l;
#line 115 "./sipCPyConverterstdvector1900.cpp"
}


sipMappedTypeDef sipTypeDef_CPyConverter_std_vector_1900 = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_121,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_std_vector_1900,
    array_std_vector_1900,
    copy_std_vector_1900,
    release_std_vector_1900,
    convertTo_std_vector_1900,
    convertFrom_std_vector_1900
};
