'\"
'\" Copyright (c) 2004  Michigan State University
'\" The TCL formatting macros have been shamelessly stolen
'\" from the httpd tcl man page:
'\"
'\" Copyright (c) 1995-1997 Sun Microsystems, Inc.
'\" Copyright (c) 1998-2000 by Ajuba Solutions.
'\"
'\" See the file "license.terms" for information on usage and redistribution
'\" of this file, and for a DISCLAIMER OF ALL WARRANTIES.
'\" 
'\" RCS: @(#) $Id$
'\" 
'\" The definitions below are for supplemental macros used in Tcl/Tk
'\" manual entries.
'\"
'\" .AP type name in/out ?indent?
'\"	Start paragraph describing an argument to a library procedure.
'\"	type is type of argument (int, etc.), in/out is either "in", "out",
'\"	or "in/out" to describe whether procedure reads or modifies arg,
'\"	and indent is equivalent to second arg of .IP (shouldn't ever be
'\"	needed;  use .AS below instead)
'\"
'\" .AS ?type? ?name?
'\"	Give maximum sizes of arguments for setting tab stops.  Type and
'\"	name are examples of largest possible arguments that will be passed
'\"	to .AP later.  If args are omitted, default tab stops are used.
'\"
'\" .BS
'\"	Start box enclosure.  From here until next .BE, everything will be
'\"	enclosed in one large box.
'\"
'\" .BE
'\"	End of box enclosure.
'\"
'\" .CS
'\"	Begin code excerpt.
'\"
'\" .CE
'\"	End code excerpt.
'\"
'\" .VS ?version? ?br?
'\"	Begin vertical sidebar, for use in marking newly-changed parts
'\"	of man pages.  The first argument is ignored and used for recording
'\"	the version when the .VS was added, so that the sidebars can be
'\"	found and removed when they reach a certain age.  If another argument
'\"	is present, then a line break is forced before starting the sidebar.
'\"
'\" .VE
'\"	End of vertical sidebar.
'\"
'\" .DS
'\"	Begin an indented unfilled display.
'\"
'\" .DE
'\"	End of indented unfilled display.
'\"
'\" .SO
'\"	Start of list of standard options for a Tk widget.  The
'\"	options follow on successive lines, in four columns separated
'\"	by tabs.
'\"
'\" .SE
'\"	End of list of standard options for a Tk widget.
'\"
'\" .OP cmdName dbName dbClass
'\"	Start of description of a specific option.  cmdName gives the
'\"	option's name as specified in the class command, dbName gives
'\"	the option's name in the option database, and dbClass gives
'\"	the option's class in the option database.
'\"
'\" .UL arg1 arg2
'\"	Print arg1 underlined, then print arg2 normally.
'\"
'\" RCS: @(#) $Id$
'\"
'\"	# Set up traps and other miscellaneous stuff for Tcl/Tk man pages.
.if t .wh -1.3i ^B
.nr ^l \n(.l
.ad b
'\"	# Start an argument description
.de AP
.ie !"\\$4"" .TP \\$4
.el \{\
.   ie !"\\$2"" .TP \\n()Cu
.   el          .TP 15
.\}
.ta \\n()Au \\n()Bu
.ie !"\\$3"" \{\
\&\\$1	\\fI\\$2\\fP	(\\$3)
.\".b
.\}
.el \{\
.br
.ie !"\\$2"" \{\
\&\\$1	\\fI\\$2\\fP
.\}
.el \{\
\&\\fI\\$1\\fP
.\}
.\}
..
'\"	# define tabbing values for .AP
.de AS
.nr )A 10n
.if !"\\$1"" .nr )A \\w'\\$1'u+3n
.nr )B \\n()Au+15n
.\"
.if !"\\$2"" .nr )B \\w'\\$2'u+\\n()Au+3n
.nr )C \\n()Bu+\\w'(in/out)'u+2n
..
.AS Tcl_Interp Tcl_CreateInterp in/out
'\"	# BS - start boxed text
'\"	# ^y = starting y location
'\"	# ^b = 1
.de BS
.br
.mk ^y
.nr ^b 1u
.if n .nf
.if n .ti 0
.if n \l'\\n(.lu\(ul'
.if n .fi
..
'\"	# BE - end boxed text (draw box now)
.de BE
.nf
.ti 0
.mk ^t
.ie n \l'\\n(^lu\(ul'
.el \{\
.\"	Draw four-sided box normally, but don't draw top of
.\"	box if the box started on an earlier page.
.ie !\\n(^b-1 \{\
\h'-1.5n'\L'|\\n(^yu-1v'\l'\\n(^lu+3n\(ul'\L'\\n(^tu+1v-\\n(^yu'\l'|0u-1.5n\(ul'
.\}
.el \}\
\h'-1.5n'\L'|\\n(^yu-1v'\h'\\n(^lu+3n'\L'\\n(^tu+1v-\\n(^yu'\l'|0u-1.5n\(ul'
.\}
.\}
.fi
.br
.nr ^b 0
..
'\"	# VS - start vertical sidebar
'\"	# ^Y = starting y location
'\"	# ^v = 1 (for troff;  for nroff this doesn't matter)
.de VS
.if !"\\$2"" .br
.mk ^Y
.ie n 'mc \s12\(br\s0
.el .nr ^v 1u
..
'\"	# VE - end of vertical sidebar
.de VE
.ie n 'mc
.el \{\
.ev 2
.nf
.ti 0
.mk ^t
\h'|\\n(^lu+3n'\L'|\\n(^Yu-1v\(bv'\v'\\n(^tu+1v-\\n(^Yu'\h'-|\\n(^lu+3n'
.sp -1
.fi
.ev
.\}
.nr ^v 0
..
'\"	# Special macro to handle page bottom:  finish off current
'\"	# box/sidebar if in box/sidebar mode, then invoked standard
'\"	# page bottom macro.
.de ^B
.ev 2
'ti 0
'nf
.mk ^t
.if \\n(^b \{\
.\"	Draw three-sided box if this is the box's first page,
.\"	draw two sides but no top otherwise.
.ie !\\n(^b-1 \h'-1.5n'\L'|\\n(^yu-1v'\l'\\n(^lu+3n\(ul'\L'\\n(^tu+1v-\\n(^yu'\h'|0u'\c
.el \h'-1.5n'\L'|\\n(^yu-1v'\h'\\n(^lu+3n'\L'\\n(^tu+1v-\\n(^yu'\h'|0u'\c
.\}
.if \\n(^v \{\
.nr ^x \\n(^tu+1v-\\n(^Yu
\kx\h'-\\nxu'\h'|\\n(^lu+3n'\ky\L'-\\n(^xu'\v'\\n(^xu'\h'|0u'\c
.\}
.bp
'fi
.ev
.if \\n(^b \{\
.mk ^y
.nr ^b 2
.\}
.if \\n(^v \{\
.mk ^Y
.\}
..
'\"	# DS - begin display
.de DS
.RS
.nf
.sp
..
'\"	# DE - end display
.de DE
.fi
.RE
.sp
..
'\"	# SO - start of list of standard options
.de SO
.SH "STANDARD OPTIONS"
.LP
.nf
.ta 5.5c 11c
.ft B
..
'\"	# SE - end of list of standard options
.de SE
.fi
.ft R
.LP
See the \\fBoptions\\fR manual entry for details on the standard options.
..
'\"	# OP - start of full description for a single option
.de OP
.LP
.nf
.ta 4c
Command-Line Name:	\\fB\\$1\\fR
Database Name:	\\fB\\$2\\fR
Database Class:	\\fB\\$3\\fR
.fi
.IP
..
'\"	# CS - begin code excerpt
.de CS
.RS
.nf
.ta .25i .5i .75i 1i
..
'\"	# CE - end code excerpt
.de CE
.fi
.RE
..
.de UL
\\$1\l'|0\(ul'\\$2
..
'\"  End of stolen macros --------------------------------

.TH "Buffer analysis framework library" 3 0.1 SpecTcl "NSCL Data analysis packages"
.BS
.SH NAME
libBufferAnalysis \- C interface to buffer analysis framework
.SH SYNOPSIS
.DS
  /* Include these:  */
  #include <config.h>
  #include <BufferAnalysis.h>
  #include <buffer.h>
  #include <buftypes.h>

  /* And you get these  */

  
  typedef void   (NSCLBufferCallback)(unsigned int, const void*, void*);

  void ProcessNSCLBuffer(const void* pBuffer); /*!< Process a single buffer */
  int  ScalersSeen();		               /*!< scalers present this run? */
  int  ScalerCount();		               /*!< # scalers this run */
  unsigned long LastIncrement(unsigned int n); /*!< increment for a channel */
  float Total(unsigned int n);                 /*!< Totals for a channel    */
  long LastIntervalStart();	               /*!< scaler interval start time   */
  long LastIntevalEnd();                       /*!< Scaler interval end time */
  const char*  Title();                        /*!< Run title. */
  unsigned int RunNumber();                    /*!< Number of current run   */
  const char*  RunStartTime();                 /*!< When the run started.  */
  const char*  RunEndTime();                   /*!< When the run ended.    */

  void AddBufferCallback(NSCLBufferCallback* cb,
			 unsigned int        type,
			 void*               userdata); /*!< add a callback */
  void RemoveBufferCallback(NSCLBufferCallback* cb,
			    unsigned int        type,
			    void*               userdata); /*!< get rid of a callback */


  /* In your code: */

  void* gpTCLApplication;

  /* Compile sort of like this */

  cc -o yourprogram yourprogram.c -I$SpecTclHome/include  -L$SpecTclHome/lib \\
        -lAnalysis -ltclPlus -lException -lBufferAnalysis

.DE
.SH DESCRIPTION
.PP
\fBBufferAnalysis\fR provides a C language programming framework for ad-hoc
analysis of NSCL data buffers.   While this framework is used within SpecTcl
for NSCL specific buffer processing, you may also use this framework to build
ad-hoc analysis programs that don't depend on SpecTcl to operate.
.PP
The software decodes buffers by buffer type and dispatches to an ordered set of
callbacks that can be established on each buffer type.  The library establishes
a standard set of callbacks to support the processing of run state transition
and scaler buffers to maintain the information that is provided by the other
functions in the library.
.PP 
See \fBEXAMPLES\fR below for more information about how to use this software.
.SH "PUBLIC INTERFACE"
.TP
\fBtypedef void   (NSCLBufferCallback)(unsigned int, const void*, void*)\fR
This typedef defines a the form of the callback functions you can register for
each buffer type.  The first parameter of your callback is the buffer type.
This allows the same callback to be registered on multiple buffer types.  The
second paramter will be a pointer to the buffer. The final parameter will be
your \fIuserdata\fR parameter to \fBAddBufferCallback\fR passed to your
callback without any interpretation.
.TP
\fBvoid ProcessNSCLBuffer(const void* \fIpBuffer\fB)\fR
Call this function to process a bufffer.  The buffer type is decoded, and all
callbacks (standard and user supplied) are invoked for the appropriate buffer
type in the order in which they were registered.  Normally your program will
register zero or more callbacks, open an event file and then, for each buffer
in the file, you will call \fBProcessBuffer\fR passing it the buffer as a
parameter.
.TP
\fBint  ScalersSeen()fR
This can be called at any time in an analysis (even from within one of your
callbacks).  \fBScalersSeen\fR will return nonzero if at least one scaler
buffer has been processed in the run being analyzed.  The functions that
retrieve
scaler data will not retrieve valid data unless \fBScalersSeen\fR would return
\fItrue\fR.
.TP
\fBint  ScalerCount()\fR
Returns the number of scalers that were read this run if \fBScalersSeen()\fR
returns \fItrue\fR. Otherwise this will return -1.
Note that all properly terminated NSCL runs will have at least one scaler
buffer, just prior to the end of run.
.TP
\fBunsigned long LastIncrement(unsigned int \fIn\fB)\fR
Returns the value of the last increment for scaler channel number \fIn\fR.
Scaler channels are numbered from 0.  If \fBScalersSeen()\fR would return
\fIfalse\fR, this will return a -1.
.TP
\fB float Total(unsigned int \fIn\fB)\fR
Returns the total number of counts read from a scaler channel \fIn\fR at this
point in the run.  This will return -1 if \fBScalerSeen\fR would return
\fIfalse\fR. 
.TP
\fBlong LastIntervalStart()\fR
Returns the number of seconds into the run at which the most recent scaler
readout interval started.  This will be -1 if \fBScalersSeen\fR would return
false.
.TP
\fBlong LastIntevalEnd()\fR
Returns the number of seconds in to the run at which the most recent scaler
readout interval ended.  This will be a -1 if \fBScalersSeen\fR would return
false.
.TP
\fBconst char*  Title()\fR
Returns a pointer to the title string that was present in the most recent
control buffer.  Control buffers include start, stop, pause, resume buffer
types.  If there has been no control buffer at this point (only possible if the
run is badly formatted enough not to contain a begin buffer, or if you have not
sent any buffers to the processing engine), this will returna pointer to an
empty string.
.TP
\fBconst char*  RunStartTime()\fR
Returns a pointer to a timestamp string that indicates when the current run was
started. This string will have the form ``Month day, year, hh:mm:ss'' 
For example, the timestamp that describes when this text was being typed in is:
``February 18, 2005, 10:32:40''
.TP
\fBconst char*  RunEndTime()\fR
Returns a pointer to a timestamp string that indicates when the current run was
ended.  This string will have the same form as the string returned by
\fBRunStartTime\fR.   If the run has seen a start buffer, but no end buffer
yet, this string will be empty.
.TP
\fBvoid AddBufferCallback(NSCLBufferCallback* \fIcb\fB, unsigned int\fBtype\fI, void* \fIuserdata\fB)\fR
Call this function to install a callback funtion on a buffer type.  The first
parameter \fIcb\fR is a pointer to your callback function.  \fItype\fR is the
type of buffer you want to install a callback on. \fIuserdata\fR is user data
that will be passed without interpretation to your function when it is called.
Note that buffer types are defined symbolically in the header \fBbuftypes.h\fR,
the structure of the buffer header and buffer bodies are described by the
structs in the header \fBbuffer.h\fR.
.TP
\fBvoid RemoveBufferCallback(NSCLBufferCallback* \fIcb\fB, unsigned int  \fItype\fB, void* \fIuserdata\fB)\fR
Call this function to remove a callback from a buffer type.  \fIcb\fR is the
pointer to the callback you established.  \fItype\fR is the buffer type on
which it was established.  \fIuserdata\fR is the userdata that was associated
with the callback.
.SH "EXAMPLES"
.PP
\fBNote\fR:  much error checking that should be done is not done in the
examples below in order to keep the brief.
.PP
The first example, processes buffers and prints out the scaler totals at the
end of a run.  Note that this requires on user callbacks.
.DS
#include <config.h>
#include <BufferAnalysis.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#include <stdio.h>
int main(int argc, char** argv)
{
  unsigned short buffer[4096];
  int fd;
  int nread;
  int i;

  fd = open(argv[1], O_RDONLY);
  
  while((nread = read(fd, buffer, sizeof(buffer))) > 0) {
    ProcessNSCLBuffer(buffer);
  }
  printf("File: %s, Run number %d, Title: %s\n Started %s Ended %s\n",
         argv[1], RunNumber(), Title(), RunStartTime(), RunEndTime());
  printf("Elapsed run time: %d seconds\n", LastIntervalEnd());
  for(i = 0; i < ScalerCount(); i++) {
    printf("Scaler channel %d total: %f\n",
           i, Total(i));
  }

  return 0;
}

.DE

.PP
The second example establishes a scaler buffer callback that prints out scaler
increments and totals for each scaler buffer.  It uses the fact that callbacks
are ordered to avoid having to actually analyze the buffer as all the
information it needs is produced by the standard callbacks.  In order to
identify the run, a begin run callback is also established.
.DS
#include <config.h>
#include <BufferAnalysis.h>
#include <buftypes.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#include <stdio.h>


void BeginCallback(unsigned int ntype, const void* pBuffer, void* pData)
{
  const char* pFilename = (const char*)pData;

  printf("Starting analysis of %s, Run %d %s\nRun started: %s\n",
	 pFilename, RunNumber(), Title(), RunStartTime());

}
void ScalerCallback(unsigned int ntype, const void* pBuffer, void* pData)
{
  int i;
  printf("---- Scalers from %d sec to %d sec elapsed time\n ----",
	 LastIntervalStart(), LastIntervalEnd());

  for(i =0; i < ScalerCount(); i++) {
    printf("Chanel %d Increments %d  Totals %d\n",
	   i, LastIncrement(i), Total(i));
  }
}


int main(int argc, char** argv)
{
  unsigned short buffer[4096];
  int fd;
  int nread;
  int i;

  fd = open(argv[1], O_RDONLY);
 
  AddBufferCallback(BeginCallback, BEGRUNBF, argv[1]);
  AddBufferCallback(ScalerCallback, SCALERBF, NULL);
 
  while((nread = read(fd, buffer, sizeof(buffer))) > 0) {
    ProcessNSCLBuffer(buffer);
  }

  printf("Run Ended %s\n", RunEndTime());

  return 0;
}
void*  gpTCLApplication;

.DE
.SH BUGS
.PP
The \fBLastIncrement\fR function can only operate over 1/2 full scale range
since it uses negative values to return errors.  This provides only 31 bits of
scaler range, while some NSCL scaler modules support 32 bits of range.

.SH "SEE ALSO"
CBufferProcessor(3), CBufferCallback(3)