//    This software is Copyright by the Board of Trustees of Michigan
//    State University (c) Copyright 2016.
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//    Authors:
//    Jeromy Tompkins
//    NSCL
//    Michigan State University
//    East Lansing, MI 48824-1321

#ifndef VIEWER_CMDLINEOPTIONS_H
#define VIEWER_CMDLINEOPTIONS_H

// generated by gengetopt
#include "cmdline.h"

#include <QString>

#include <vector>
#include <string>

namespace Viewer {


/*!
 * \brief A wrapper around the gengetopt parser structure
 *
 * It is very simple and provides access to the various command line option
 * values.
 */
class CmdLineOptions
{
    // All source code documentation is in source file. See doxygen output.

private:
    std::vector<std::string>  m_args;
    gengetopt_args_info       m_info;

public:
    CmdLineOptions();

    void parse(int argc, char* argv[]);

    int getPort();

    QString getHost();

    /*! \returns whether the user specified the --disable-truetype or -t options */
    bool disableTrueTypeFonts() const;
};

} // namespace Viewer

#endif // VIEWER_CMDLINEOPTIONS_H
