//    This software is Copyright by the Board of Trustees of Michigan
//    State University (c) Copyright 2015.
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//    Authors:
//    Jeromy Tompkins 
//    NSCL
//    Michigan State University
//    East Lansing, MI 48824-1321

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "SpecTclInterfaceControl.h"

#include <QMainWindow>


// Forward declaration of UI class (generated by uic)
namespace Ui {
class MainWindow;
}


namespace Viewer
{


// Forward declarations
class SpectrumView;
class HistogramView;
class DockableGateManager;
class SpecTclInterface;
class ControlPanel;

/*!
 * \brief The MainWindow class
 *
 * This is main window. It handles the menus, the view, the control panel,
 * and the dockable widgets.
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    /*!
     * \brief Constructor
     *
     * \param parent - the parent widget
     */
    explicit MainWindow(QWidget *parent = 0);

    /*!
     * \brief Destructor
     */
    ~MainWindow();

    /*!
     * \brief Constructs the dockable widgets
     *
     * The dockable widgets are the gate manager (DockableGateManager)
     * and the histogram manager (HistogramView).
     */
    void createDockWindows();

    /*!
     * \brief Replace the SpecTclInterface with a new one
     *
     * \param pInterface the new interface
     *
     * This handles the connection of some of the signals and slots
     */
    void setSpecTclInterface(std::unique_ptr<SpecTclInterface> pInterface);


    ///////////////////////////////////////////////////////////////////////////

public slots:

    /*!
     * \brief onConnect
     */
    void onConfigure();
    void dockHistograms();
    void dockGates();

    void onNewHistogram();

    ///////////////////////////////////////////////////////////////////////////
private:
    Ui::MainWindow                    *ui;
    SpectrumView                      *m_pView;
    HistogramView                     *m_histView;
    DockableGateManager               *m_gateView;
    SpecTclInterfaceControl           m_specTclControl;
    ControlPanel                      *m_pControls;
};



} // end of namespace
#endif // MAINWINDOW_H
