#!/bin/sh

set -x
find . -name .deps -exec rm -rf {} \;
find . -name "*.o" -exec rm {} \;
aclocal -I config
libtoolize --force --copy
autoheader
automake --add-missing --copy
autoconf --warnings=none
