C
C	THE  COMMON AREA FOR THE AED DISPLAY PROGRAM
C
C
	PARAMETER AED_ISMAX=999
	PARAMETER AED_BYTES=1048576*8
	PARAMETER AED_WORDS=AED_BYTES/2
	PARAMETER AED_LONGS=AED_BYTES/4
	PARAMETER AED_PAGES=AED_BYTES/512
C
	DIMENSION AED_DATA1(AED_BYTES)
	1	  ,AED_DATA2(AED_WORDS)
	2	  ,AED_DATA4(AED_LONGS)
	EQUIVALENCE (AED_DATA1,AED_DATA2),(AED_DATA1,AED_DATA4)
	LOGICAL*1 AED_DATA1
	INTEGER*2 AED_DATA2
	INTEGER*4 AED_DATA4
C
C	DISPLAY CONTROL AREA
C
	DIMENSION AED_BUSY(AED_ISMAX),AED_LOCK(AED_ISMAX),AED_XY(2,AED_ISMAX)
	1,AED_TITLE(70,AED_ISMAX),AED_OFFSET(AED_ISMAX),AED_TYPE(AED_ISMAX)
	2,AED_POINT(AED_ISMAX),AED_BLOCKS(AED_ISMAX*28)
C
	LOGICAL*1 AED_BUSY,AED_LOCK,AED_TYPE,AED_TITLE
C
	INTEGER*2 AED_XY,AED_POINT,AED_BLOCKS,AED_FREE
C
	INTEGER*4 AED_OFFSET
C
C	CONTROL IS READ WRITE
C
	COMMON/SPEC_SHARED/ aed_xy, aed_title, aed_offset, aed_type,
     1                      AED_DATA1
	VOLATILE SPEC_SHARED

