C
C Facility:
C   Xamine  - NSCL display program.
C Abstract:
C   AEDSHARE.FOR:
C     This file provides compatibility between XAMINE and the old AEDTSK by
C     providing equivalences between the AEDTSK shared variables and the
C     Xamine shared variables.
C Author:
C     Ron FOx
C     NSCL
C     Michigan State University
C     East Lansing, MI 48824-1321
C     October 18, 1993
C
	INTEGER AED_BYTES, AED_WORDS, AED_LONGS
	PARAMETER (AED_BYTES=1048576*8)
	PARAMETER (AED_WORDS=AED_BYTES/2)
	PARAMETER (AED_LONGS=AED_BYTES/4)

	INTEGER XAMINE_SPECBYTES
	PARAMETER (XAMINE_SPECBYTES = AED_BYTES)
	INCLUDE 'xamineshare.for'
C
	INTEGER AED_ISMAX
	PARAMETER (AED_ISMAX = XAMINE_ISMAX)

	DIMENSION AED_DATA1(AED_BYTES)
	1	  ,AED_DATA2(AED_WORDS)
	2	  ,AED_DATA4(AED_LONGS)

	LOGICAL*1 AED_DATA1
	INTEGER*2 AED_DATA2
	INTEGER*4 AED_DATA4

	INTEGER*2 AED_XY(2,AED_ISMAX)
	BYTE      AED_TITLE(72, AED_ISMAX)
	INTEGER   AED_OFFSET(AED_ISMAX)
	INTEGER   AED_TYPE(AED_ISMAX)

	POINTER  (AED_XYPTR,     AED_XY)
	POINTER  (AED_TITLEPTR,  AED_TITLE)
	POINTER  (AED_OFFSETPTR, AED_OFFSET)
	POINTER  (AED_TYPEPTR,   AED_TYPE)
	POINTER  (AED_DATA1PTR,  AED_DATA1)
	POINTER  (AED_DATA2PTR,  AED_DATA2)
	POINTER  (AED_DATA4PTR,  AED_DATA4)

	COMMON/AED_SHARED/AED_XYPTR, AED_TITLEPTR, AED_OFFSETPTR,
	1     	          AED_TYPEPTR, AED_DATA1PTR, AED_DATA2PTR,
	1		  AED_DATA4PTR

C
C     Cannot declare the functions since ULTRIX bitches inside the functions.
C

