#
#   Make axis scaling classes and tests.
#



cppunithome="/user/fox/cppunit"

CLASSES=CParameterMapping.o CAxis.o
INCLUDES=-I../Utility $(shell $(cppunithome)/bin/cppunit-config --cflags)
LDFLAGS=$(shell $(cppunithome)/bin/cppunit-config --libs)

CPP=g++ -g -c $(INCLUDES)
LD=g++ -g

SUITES = CParameterMappingTest.o CAxisTests.o


.cpp.o:
	$(CPP) $<

all:  Implementations tests

tests: ScalingTests 


Implementations: $(CLASSES)


ScalingTests: ScalingTests.o $(SUITES) $(CLASSES)
	$(LD) -o ScalingTests ScalingTests.o $(SUITES) $(CLASSES) $(LDFLAGS)





# DO NOT DELETE

AnalysisTest.o: Histogrammer.h Dictionary.h Parameter.h /usr/include/limits.h
AnalysisTest.o: /usr/include/features.h /usr/include/sys/cdefs.h
AnalysisTest.o: /usr/include/gnu/stubs.h
AnalysisTest.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
AnalysisTest.o: Spectrum.h Spectrum1DL.h Spectrum2DW.h Spectrum2DB.h
AnalysisTest.o: Spectrum1DW.h Gamma1DW.h Gamma1DL.h Gamma2DW.h Gamma2DB.h
CAxisTests.o: CAxisTests.h CAxis.h CParameterMapping.h
CParameterMappingTest.o: CParameterMappingTest.h CParameterMapping.h
CParameterMappingTest.o: /usr/include/stdlib.h /usr/include/features.h
CParameterMappingTest.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
CParameterMappingTest.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
ScalingTests.o: CParameterMappingTest.h CParameterMapping.h CAxisTests.h
ScalingTests.o: CAxis.h
CAxis.o: CAxis.h CParameterMapping.h
CParameterMapping.o: CParameterMapping.h
